### PR TITLE
Update doc for Quick Base custom merge field

### PR DESCRIPTION
**Pull request by zweedao**
https://github.com/workato/workato/pull/20843#event-1985843431

### CODE REVIEW

**Comment by zweedao** [comment]
@ashaevan can you help to review if the behavior of custom merge field is correct

@graceliching can you help to review overall write-up

Thanks 👌

**Comment by gopiganesh** [comment]
@zweedao 
When Merge field is `Order ID` and Key is `RecordID#` (QB UI), action updated existing if Order ID is matching, if not created. If Order ID has no value/empty - action created new row.

When Merge field is `Order ID` and key is `Order ID` (QB UI), action updated existing if Order ID is matching, if not matching - error (Error text: New record can't be added on the table where key field is not Record ID), if left empty - error (Error text: Invalid input: New record can't be added on the table where key field is not Record ID.)

@ashaevan Please confirm.

**Comment by ashaevan** [comment]
@gopiganesh That's right!

**Comment by zweedao** [comment]
@graceliching how's your review

**Comment by graceliching** [comment]
@zweedao Sorry, couldn't get to reviewing while overseas. I looked and it doesn't seem like 'custom merge field' is a term that is familiar to QB customers. Can we make sure this is explained somewhere or make sure this is the right terminology? 

Is a merge field just a normal field or a special field type? Other than that, I think it's good.

**Comment by zweedao** [comment]
@graceliching custom merge field is a new feature released by Quick Base. They don't have a doc for it yet. Just communicated with us via email. I put some explanation here:
screen shot 2018-12-04 at 2 50 19 pm

**Comment by graceliching** [comment]
@zweedao I see. Merged.

**Pull request merged**
