### PR TITLE
Add parts about RFC in SAP

### PR DESCRIPTION
**Pull request by zweedao**

### CODE REVIEW

**Comment by zweedao** [comment]
Finally passed CI. @graceliching can you merge :)

**Comment by zweedao** [comment]
@graceliching I don't see this update on Production yet. Something wrong?

**Comment by graceliching** [comment]
@zweedao let me check

**Comment by graceliching** [comment]
@zweedao it was merged, but not deployed. Any idea how to check?

**Comment by zweedao** [comment]
@graceliching I think you need to ping Harish & Dimitris

**Pull request merged**
