### PR TITLE
product updates - 27/02/2020

### PR DESCRIPTION
**Pull request by madddygoh**
added recipe editor design updates, gdrive new trigger (file/folder in folder) and billing dashboard updates

### CODE REVIEW

**Comment by graceliching** [comment]
Have some comments on readability for Maddy and Scott

**Comment by graceliching** [comment]
@eeshansim @bennettgo @jandonyada anything to add?

**Comment by eeshansim** [comment]
- Anaplan migration to v2 API (CA cert support)
- Data retention
- Zendesk basic authentication
- Amazon S3 presigned URL action
- Marketo lead activity bulk export

**Comment by graceliching** [comment]
@eeshansim Do you want to commit directly to the doc? Will need a couple of lines on each, I think there's already something on prod announce for data retention so I can ask Scott to add that

**Comment by graceliching** [comment]
@eeshansim-- the updates you mentioned will have to be on another PR, the prod marketing team needs this live for the newsletter.

**Pull request merged**
