### PR TITLE
API table styles

### PR DESCRIPTION
**Pull request by graceliching**
@th0r Hi Yuriy, can you help take a look at this PR and see why the table styles do not apply to some tables:

Eg. below where table width should be 100%: 
image

Thank you!

### CODE REVIEW

**Comment by graceliching** [comment]
I think we should disable the auto-scaling of the table to a shorter width, it makes multiple tables in the same article look messy
image

**Comment by th0r** [comment]
@graceliching fixed

**Comment by th0r** [comment]
@graceliching what do you think about this plugin? https://github.com/arve0/markdown-it-attrs
It allows to set any attributes to any markdown tag. In case of tables it will look like this:
```md
| Name  | Description  | Sample reply                  |
|-------|--------------|-------------------------------|
| `200` | Success      | `{"Success": true}`           |
| `400` | Bad request  | `{"message": "Bad request"}`  |
| `401` | Unauthorized | `{"message": "Unauthorized"}` |
| `404` | Not found    | `{"message": "Not found"}`    |
| `500` | Server error | `{"message":"Server error","id":"3188c2d0-29a4-4080-908e-582e7ed82580"}` |
{.api_input}
```
I tried it and it works.

**Comment by graceliching** [comment]
> @graceliching what do you think about this plugin? https://github.com/arve0/markdown-it-attrs
> It allows to set any attributes to any markdown tag. In case of tables it will look like this:
> 
> ```lisp
> | Name  | Description  | Sample reply                  |
> |-------|--------------|-------------------------------|
> | `200` | Success      | `{"Success": true}`           |
> | `400` | Bad request  | `{"message": "Bad request"}`  |
> | `401` | Unauthorized | `{"message": "Unauthorized"}` |
> | `404` | Not found    | `{"message": "Not found"}`    |
> | `500` | Server error | `{"message":"Server error","id":"3188c2d0-29a4-4080-908e-582e7ed82580"}` |
> {.api_input}
> ```
> 
> I tried it and it works.

Thank you! Great, I think it looks cleaner than the way it is today. @th0r

**Comment by th0r** [comment]
> Thank you! Great, I think it looks cleaner than the way it is today.

Done

**Pull request merged**
